apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: broken-webhook
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: non-existing-hagkixhb
        namespace: non-existing-pztjqmkx
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: webhook.non-existing.dev
    namespaceSelector: {}
    objectSelector:
      matchLabels:
        serving.knative.dev/service: deployment-upgrade-failure
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
    timeoutSeconds: 5